#config.yaml
TYPES: ['MEDECIN', 'PATIENT', 'DOCUMENT']
ENTITIES: (['ADELI', 'RPPS', 'NAME', 'FINESS', 'ADRESSE', 'TELEPHONE'], ['NAME', 'SECU', 'ADRESSE'], ['MONTANT', 'DATE', 'MENTION'])
TITLE: 'NLP Annotator'
FOLDER: 'files'
STORAGE: 'memory'